config/routes.rb
Rails.application.routes.draw do
  devise_for :profs
  devise_for :admins
  root 'home#inicio'
  resources :historicos
  resources :alunos
  resources :turmas
  resources :professors
  resources :secretarios
  devise_for :user
  get 'secretario', to: 'secretarios#opcoes_secretario'
  get 'aluno', to: 'alunos#opcoes_aluno'
  get 'professor', to: 'professors#opcoes_professor'
  get 'secretario1', to: 'secretarios#index'
  get 'aluno1', to: 'alunos#index'
  get 'professor1', to: 'professors#index'
  get 'aluno_historico', to: 'historicos#index'
  get 'turma', to: 'turmas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/turma.rb
class Turma < ApplicationRecord
  belongs_to :professor
  has_many :aluno
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
    @aluno = Aluno.all
    @professor = Professor
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
    @aluno = Aluno.all
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params
      params.require(:turma).permit(:nome, :nivel, :professor_id, :professor, :aluno)
    end
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/turmas/_form.html.erb
<%= form_with(model: turma, local: true) do |form| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
        <% turma.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :nivel %>
    <%= form.number_field :nivel %>
  </div>

  <div class="field">
    <%= form.label :professor %>
    <%= collection_select(:turma, :professor_id, Professor.all, :id, :nome) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nivel</th>
      <th>Professor</th>
      <th>Alunos</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
      <% if prof_signed_in? && @professor.ids==turma.professor.id%>
        <td><%= turma.nome %></td>
        <td><%= turma.nivel %></td>
        <td><%= turma.professor.nome %></td>
        <td><%= 'Clique em show para ver os alunos' %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% elsif admin_signed_in? %>
        <td><%= turma.nome %></td>
        <td><%= turma.nivel %></td>
        <td><%= turma.professor.nome %></td>
        <td><%= 'Clique em show para ver os alunos' %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <%= link_to 'Voltar', 'secretario' %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @turma.nome %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @turma.nivel %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @turma.professor.nome %>
</p>

<p>
  <strong>Alunos:</strong>
  <% @aluno.each do |aluno| %>
    <% if aluno.turma.id == @turma.id %>
   |  <%= aluno.nome %> |
     <% end %>
  <% end %> 
  </p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>