config/routes.rb
Rails.application.routes.draw do
  devise_for :profs
  devise_for :admins
  root 'home#inicio'
  resources :historicos
  resources :alunos
  resources :turmas
  resources :professors
  resources :secretarios
  devise_for :user
  get 'secretario', to: 'secretarios#opcoes_secretario'
  get 'aluno', to: 'alunos#opcoes_aluno'
  get 'professor', to: 'professors#opcoes_professor'
  get 'secretario1', to: 'secretarios#index'
  get 'aluno1', to: 'alunos#index'
  get 'professor1', to: 'professors#index'
  get 'aluno_historico', to: 'historicos#index'
  get 'turma', to: 'turmas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/secretario.rb
class Secretario < ApplicationRecord
    #has_many :admin
end

app/controllers/secretarios_controller.rb
class SecretariosController < ApplicationController
  before_action :set_secretario, only: [:show, :edit, :update, :destroy]

  def opcoes_secretario
    authenticate_admin!
    #load_and_authorize_resource
  end
  # GET /secretarios
  # GET /secretarios.json
  def index
    @secretarios = Secretario.all
  end

  # GET /secretarios/1
  # GET /secretarios/1.json
  def show
  end

  # GET /secretarios/new
  def new
    @secretario = Secretario.new
  end

  # GET /secretarios/1/edit
  def edit
  end

  # POST /secretarios
  # POST /secretarios.json
  def create
    @secretario = Secretario.new(secretario_params)

    respond_to do |format|
      if @secretario.save
        format.html { redirect_to @secretario, notice: 'Secretario was successfully created.' }
        format.json { render :show, status: :created, location: @secretario }
      else
        format.html { render :new }
        format.json { render json: @secretario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secretarios/1
  # PATCH/PUT /secretarios/1.json
  def update
    respond_to do |format|
      if @secretario.update(secretario_params)
        format.html { redirect_to @secretario, notice: 'Secretario was successfully updated.' }
        format.json { render :show, status: :ok, location: @secretario }
      else
        format.html { render :edit }
        format.json { render json: @secretario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secretarios/1
  # DELETE /secretarios/1.json
  def destroy
    @secretario.destroy
    respond_to do |format|
      format.html { redirect_to secretarios_url, notice: 'Secretario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secretario
      @secretario = Secretario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secretario_params
      params.require(:secretario).permit(:nome, :identificacao)
    end
end

app/helpers/secretarios_helper.rb
module SecretariosHelper
end

app/views/secretarios/_form.html.erb
<%= form_with(model: secretario, local: true) do |form| %>
  <% if secretario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secretario.errors.count, "error") %> prohibited this secretario from being saved:</h2>

      <ul>
        <% secretario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :identificacao %>
    <%= form.text_field :identificacao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/secretarios/edit.html.erb
<h1>Editing Secretario</h1>

<%= render 'form', secretario: @secretario %>

<%= link_to 'Show', @secretario %> |
<%= link_to 'Back', secretarios_path %>

app/views/secretarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Secretarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Identificacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secretarios.each do |secretario| %>
      <tr>
        <td><%= secretario.nome %></td>
        <td><%= secretario.identificacao %></td>
        <td><%= link_to 'Show', secretario %></td>
        <td><%= link_to 'Edit', edit_secretario_path(secretario) %></td>
        <td><%= link_to 'Destroy', secretario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secretario', new_secretario_path %>

app/views/secretarios/new.html.erb
<h1>New Secretario</h1>

<%= render 'form', secretario: @secretario %>

<%= link_to 'Back', secretarios_path %>

app/views/secretarios/opcoes_secretario.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UNB Idiomas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <p class="navbar-text float-right">
  <% if admin_signed_in? %>
  Logado como: <strong><%= current_admin.email %></strong>.
  <%= link_to 'Editar perfil', edit_admin_registration_path, :class => 'navbar-link' %> 
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %> <br> <br>
  | <%= link_to 'Criar secretário', 'secretario1' %> | <br> 
  | <%= link_to 'Criar aluno', 'aluno1' %> | <br>
  | <%= link_to 'Criar professor', 'professor1' %> | <br>
  | <%= link_to 'Criar turma', 'turma' %> | <br> 
  <% else %>
  <%= link_to "Registrar-se", new_admin_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/secretarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @secretario.nome %>
</p>

<p>
  <strong>Identificacao:</strong>
  <%= @secretario.identificacao %>
</p>

<%= link_to 'Edit', edit_secretario_path(@secretario) %> |
<%= link_to 'Back', secretarios_path %>