config/routes.rb
Rails.application.routes.draw do
  devise_for :profs
  devise_for :admins
  root 'home#inicio'
  resources :historicos
  resources :alunos
  resources :turmas
  resources :professors
  resources :secretarios
  devise_for :user
  get 'secretario', to: 'secretarios#opcoes_secretario'
  get 'aluno', to: 'alunos#opcoes_aluno'
  get 'professor', to: 'professors#opcoes_professor'
  get 'secretario1', to: 'secretarios#index'
  get 'aluno1', to: 'alunos#index'
  get 'professor1', to: 'professors#index'
  get 'aluno_historico', to: 'historicos#index'
  get 'turma', to: 'turmas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
  #has_many :turma
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  def opcoes_professor
    authenticate_prof!
    #load_and_authorize_resource
  end
  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :matricula, :formacao)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :formacao %>
    <%= form.text_field :formacao %>
  </div>

  <div class="field">
     <%= link_to 'criar login professor', new_prof_registration_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Formacao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.nome %></td>
        <td><%= professor.matricula %></td>
        <td><%= professor.formacao %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= link_to 'Voltar', 'secretario' %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/opcoes_professor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UNB Idiomas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <p class="navbar-text float-right">
  <% if prof_signed_in? %>
  Logado como: <strong><%= current_prof.email %></strong>.
  <%= link_to 'Editar perfil', edit_prof_registration_path, :class => 'navbar-link' %> 
  <%= link_to "Logout", destroy_prof_session_path, method: :delete, :class => 'navbar-link'  %> <br> <br>
  | <%= link_to 'Criar turma', 'turma' %> | <br> 
  <% else %>
  <%= link_to "Registrar-se", new_prof_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_prof_session_path, :class => 'navbar-link'  %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professor.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @professor.matricula %>
</p>

<p>
  <strong>Formacao:</strong>
  <%= @professor.formacao %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>