config/routes.rb
Rails.application.routes.draw do
  devise_for :profs
  devise_for :admins
  root 'home#inicio'
  resources :historicos
  resources :alunos
  resources :turmas
  resources :professors
  resources :secretarios
  devise_for :user
  get 'secretario', to: 'secretarios#opcoes_secretario'
  get 'aluno', to: 'alunos#opcoes_aluno'
  get 'professor', to: 'professors#opcoes_professor'
  get 'secretario1', to: 'secretarios#index'
  get 'aluno1', to: 'alunos#index'
  get 'professor1', to: 'professors#index'
  get 'aluno_historico', to: 'historicos#index'
  get 'turma', to: 'turmas#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/historico.rb
class Historico < ApplicationRecord
  #belongs_to :aluno
end

app/controllers/historicos_controller.rb
class HistoricosController < ApplicationController
  before_action :set_historico, only: [:show, :edit, :update, :destroy]

  # GET /historicos
  # GET /historicos.json
  def index
    @historicos = Historico.all
  end

  # GET /historicos/1
  # GET /historicos/1.json
  def show
  end

  # GET /historicos/new
  def new
    @historico = Historico.new
  end

  # GET /historicos/1/edit
  def edit
  end

  # POST /historicos
  # POST /historicos.json
  def create
    @historico = Historico.new(historico_params)

    respond_to do |format|
      if @historico.save
        format.html { redirect_to @historico, notice: 'Historico was successfully created.' }
        format.json { render :show, status: :created, location: @historico }
      else
        format.html { render :new }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historicos/1
  # PATCH/PUT /historicos/1.json
  def update
    respond_to do |format|
      if @historico.update(historico_params)
        format.html { redirect_to @historico, notice: 'Historico was successfully updated.' }
        format.json { render :show, status: :ok, location: @historico }
      else
        format.html { render :edit }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historicos/1
  # DELETE /historicos/1.json
  def destroy
    @historico.destroy
    respond_to do |format|
      format.html { redirect_to historicos_url, notice: 'Historico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historico
      @historico = Historico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historico_params
      params.require(:historico).permit(:aluno_id, :turma_id, :mencao)
    end
end

app/helpers/historicos_helper.rb
module HistoricosHelper
end

app/views/historicos/_form.html.erb
<%= form_with(model: historico, local: true) do |form| %>
  <% if historico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historico.errors.count, "error") %> prohibited this historico from being saved:</h2>

      <ul>
        <% historico.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.text_field :aluno_id %>
  </div>

  <div class="field">
    <%= form.label :turma_id %>
    <%= form.number_field :turma_id %>
  </div>

  <div class="field">
    <%= form.label :mencao %>
    <%= form.text_field :mencao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/historicos/edit.html.erb
<h1>Editing Historico</h1>

<%= render 'form', historico: @historico %>

<%= link_to 'Show', @historico %> |
<%= link_to 'Back', historicos_path %>

app/views/historicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historicos</h1>

<table>
  <thead>
    <tr>
      <th>Aluno</th>
      <th>Turma</th>
      <th>Mencao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historicos.each do |historico| %>
      <tr>
        <td><%= historico.aluno_id %></td>
        <td><%= historico.turma_id %></td>
        <td><%= historico.mencao %></td>
        <td><%= link_to 'Show', historico %></td>
        <td><%= link_to 'Edit', edit_historico_path(historico) %></td>
        <td><%= link_to 'Destroy', historico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historico', new_historico_path %>

app/views/historicos/new.html.erb
<h1>New Historico</h1>

<%= render 'form', historico: @historico %>

<%= link_to 'Back', historicos_path %>

app/views/historicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aluno:</strong>
  <%= @historico.aluno_id %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @historico.turma_id %>
</p>

<p>
  <strong>Mencao:</strong>
  <%= @historico.mencao %>
</p>

<%= link_to 'Edit', edit_historico_path(@historico) %> |
<%= link_to 'Back', historicos_path %>